export const modalKeys = [
  "dashboard.export",
  "dashboard.edit-ticket",
  "equipment.create",
  "equipment.view",
  "equipment.edit",
  "equipment.delete",
  "equipment.qr-scan",
  "equipment.transfer-history",
  "maintenance.create",
  "maintenance.view",
  "maintenance.edit",
  "maintenance.delete",
  "maintenance.history",
  "maintenance.calendar",
  "tickets.create",
  "tickets.edit",
  "tickets.delete",
  "chat.create",
  "chat.info",
  "chat.members",
  "chat.clear-history",
  "chat.delete",
  "users.create",
  "users.view",
  "users.edit",
  "users.delete",
  "locations.create",
  "locations.view",
  "locations.edit",
  "locations.delete",
  "locations.equipment",
  "departments.create",
  "departments.edit",
  "departments.delete",
  "positions.create",
  "positions.edit",
  "positions.delete",
] as const;

export type ModalKey = typeof modalKeys[number];

export const modalTitleMap: Partial<Record<ModalKey, string>> = {
  "dashboard.export": "Экспорт данных",
  "dashboard.edit-ticket": "Редактировать заявку",
  "equipment.create": "Добавить оборудование",
  "equipment.view": "Карточка оборудования",
  "equipment.edit": "Редактировать оборудование",
  "equipment.delete": "Удалить оборудование",
  "equipment.qr-scan": "Сканирование QR",
  "equipment.transfer-history": "История передач",
  "maintenance.create": "Запланировать ТО",
  "maintenance.view": "Просмотр ТО",
  "maintenance.edit": "Редактировать ТО",
  "maintenance.delete": "Удалить запись ТО",
  "maintenance.history": "История обслуживания",
  "maintenance.calendar": "Календарь ТО",
  "tickets.create": "Создать заявку",
  "tickets.edit": "Редактировать заявку",
  "tickets.delete": "Удалить заявку",
  "chat.create": "Создать новый чат",
  "chat.info": "Информация о чате",
  "chat.members": "Участники чата",
  "chat.clear-history": "Очистить историю",
  "chat.delete": "Удалить чат",
  "users.create": "Добавить пользователя",
  "users.view": "Профиль пользователя",
  "users.edit": "Редактировать пользователя",
  "users.delete": "Удалить пользователя",
  "locations.create": "Добавить локацию",
  "locations.view": "Информация о локации",
  "locations.edit": "Редактировать локацию",
  "locations.delete": "Удалить локацию",
  "locations.equipment": "Оборудование локации",
  "departments.create": "Добавить отдел",
  "departments.edit": "Редактировать отдел",
  "departments.delete": "Удалить отдел",
  "positions.create": "Добавить должность",
  "positions.edit": "Редактировать должность",
  "positions.delete": "Удалить должность",
};
